server.port=8082
spring.application.name=event-service
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Forward Headers for Proxy
server.forward-headers-strategy=FRAMEWORK

# SpringDoc Prefixed Paths
springdoc.api-docs.path=/events/v3/api-docs
springdoc.swagger-ui.path=/events/swagger-ui.html
springdoc.swagger-ui.config-url=/events/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/events/v3/api-docs

# Eureka & JWT
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
jwt.secret=${JWT_SECRET:9a4f4e35455ad3b246a4d538e78f99e82104323e4213a4f6789a44c1d2e3f4a5}
jwt.expiration=${JWT_EXPIRATION:86400000}
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8081}

# Database - LOCAL (commented out to use NeonDB)
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://event-db:5432/event_db}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:user}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Database - NEONDB (active)
spring.datasource.url=jdbc:postgresql://ep-floral-moon-ad2xk7dc-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VYbw2NX4SZPr
